from __future__ import annotations

from rest_framework import serializers

from apps.cash.models import CashRegister
from apps.catalog.serializers import BrandSerializer, CategorySerializer, ProductVariantSerializer
from apps.core.fields import TenantPrimaryKeyRelatedField
from apps.core.serializers import TenantModelSerializer
from apps.customers.serializers import CustomerSerializer
from apps.inventory.serializers import StockLevelSerializer
from apps.organizations.models import Location

from .models import Device, SyncOperation

# A batch has to fit in one request and one transaction budget. A till that
# was offline for a week sends several batches, which is fine.
MAX_OPERATIONS_PER_PUSH = 200


class DeviceSerializer(TenantModelSerializer):
    location_name = serializers.CharField(source="location.name", read_only=True)

    class Meta:
        model = Device
        fields = [
            "id",
            "identifier",
            "name",
            "location",
            "location_name",
            "cash_register",
            "platform",
            "app_version",
            "is_active",
            "last_seen_at",
            "last_sync_at",
            "created_at",
        ]
        read_only_fields = ["id", "last_seen_at", "last_sync_at", "created_at"]


class DeviceRegistrationSerializer(serializers.Serializer):
    """Registering the same identifier twice updates the device, never duplicates it."""

    identifier = serializers.CharField(max_length=64)
    name = serializers.CharField(max_length=80)
    location = TenantPrimaryKeyRelatedField(queryset=Location.objects, required=False)
    cash_register = TenantPrimaryKeyRelatedField(
        queryset=CashRegister.objects, required=False, allow_null=True
    )
    platform = serializers.CharField(max_length=40, required=False, allow_blank=True)
    app_version = serializers.CharField(max_length=20, required=False, allow_blank=True)


class SyncOperationSerializer(TenantModelSerializer):
    device_name = serializers.CharField(source="device.name", read_only=True)

    class Meta:
        model = SyncOperation
        fields = [
            "id",
            "operation_id",
            "device",
            "device_name",
            "operation_type",
            "status",
            "payload",
            "result",
            "error_code",
            "error_detail",
            "occurred_at",
            "received_at",
        ]
        read_only_fields = fields


class SyncOperationInputSerializer(serializers.Serializer):
    operation_id = serializers.UUIDField(
        help_text="Generated by the terminal. Replaying it is a no-op."
    )
    operation_type = serializers.ChoiceField(choices=SyncOperation.Type.choices)
    occurred_at = serializers.DateTimeField(
        required=False, help_text="When the terminal performed it, offline."
    )
    payload = serializers.DictField()


class SyncPushSerializer(serializers.Serializer):
    device = TenantPrimaryKeyRelatedField(queryset=Device.objects)
    operations = SyncOperationInputSerializer(many=True)

    def validate_operations(self, value):
        if not value:
            raise serializers.ValidationError("Send at least one operation.")
        if len(value) > MAX_OPERATIONS_PER_PUSH:
            raise serializers.ValidationError(
                f"At most {MAX_OPERATIONS_PER_PUSH} operations per push."
            )
        ids = [str(op["operation_id"]) for op in value]
        if len(set(ids)) != len(ids):
            raise serializers.ValidationError("Duplicate operation_id inside the same batch.")
        return value

    def validate_device(self, value):
        if not value.is_active:
            raise serializers.ValidationError("This device is deactivated.")
        return value


class SyncPushResultSerializer(serializers.Serializer):
    operation_id = serializers.UUIDField()
    operation_type = serializers.CharField(required=False)
    status = serializers.CharField()
    duplicate = serializers.BooleanField()
    result = serializers.DictField(allow_null=True)
    error_code = serializers.CharField(allow_null=True)
    detail = serializers.CharField(allow_null=True)


class SyncPullSerializer(serializers.Serializer):
    """The delta a terminal applies to its local database."""

    cursor = serializers.DateTimeField()
    since = serializers.DateTimeField(allow_null=True)
    categories = CategorySerializer(many=True)
    brands = BrandSerializer(many=True)
    products = serializers.SerializerMethodField()
    variants = ProductVariantSerializer(many=True)
    customers = CustomerSerializer(many=True)
    stock = StockLevelSerializer(many=True)

    def get_products(self, obj) -> list:
        # Products are sent without their nested variants: the variants array
        # already carries them, and duplicating would double the payload.

        return [
            {
                "id": str(product.pk),
                "name": product.name,
                "category": str(product.category_id) if product.category_id else None,
                "brand": str(product.brand_id) if product.brand_id else None,
                "track_inventory": product.track_inventory,
                "is_active": product.is_active,
            }
            for product in obj["products"]
        ]
